spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://root:ERg8pdChuS2eJ56kZQKfKIXhKRmEyjyy@ufe5pw.stackhero-network.com/root?useSSL=true&requireSSL=true"
#    username: root
#    password: 9ol.)P:?
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  sql:
#    init:
#      mode: always
  jpa:

    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  #Cloudinary Properties
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:
